# Generated by Django 5.1.2 on 2024-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
