# Generated by Django 5.1.2 on 2024-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0003_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='names',
            field=models.CharField(default='name', max_length=1000),
        ),
    ]
