# Generated by Django 5.1.2 on 2024-10-29 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0005_remove_contact_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='cont',
        ),
    ]
