# Generated by Django 5.1.2 on 2024-10-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0006_rename_contact_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=1000)),
                ('mobiles', models.CharField(max_length=10)),
                ('desig', models.CharField(max_length=1000)),
                ('text', models.TextField(max_length=500)),
                ('sug_f', models.CharField(max_length=100)),
                ('emails', models.EmailField(max_length=100)),
                ('classes', models.CharField(max_length=1000)),
            ],
        ),
    ]
