# Generated by Django 5.1.2 on 2024-10-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0007_suggest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggest',
            old_name='names',
            new_name='mem',
        ),
    ]
