# Generated by Django 5.1.2 on 2024-10-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0008_rename_names_suggest_mem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggest',
            new_name='suggests',
        ),
    ]
