# Generated by Django 5.1.2 on 2024-10-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrita', '0010_remove_suggests_mobiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.CharField(default='-', max_length=2),
        ),
    ]
